var albumList = [{
    albumName: 'Dark Side of the Moon',
    photos: [{source:'app/images/dark01.jpg',
              caption: 'In all its majesty'},
             {source:'app/images/dark02.jpg',
              caption: 'Black and White Chic'},
             {source:'app/images/dark03.jpg',
              caption: 'At the barber'},
             {source:'app/images/dark04.jpg',
              caption: 'Live at Stonehenge, 1977'},
             {source:'app/images/dark05.jpg',
              caption: 'Live in Moscow, 1983'},
             {source:'app/images/dark06.jpg',
              caption: 'Beach Vacation'}]
}, {
    albumName: 'Intense Space',
    photos: [{source:'app/images/space02.jpg',
              caption: 'Gnarly Gnebula'},
             {source:'app/images/space01.jpg',
              caption: 'Quool Quasar'},
             {source:'app/images/space03.jpg',
              caption: 'Space is big'},
             {source:'app/images/space04.jpg',
              caption: 'People are small'},
             {source:'app/images/space05.jpg',
              caption: 'Space Fantasy'}]
}, {
    albumName: 'The Grand Wazoo',
    photos: [{source:'app/images/wazoo01.jpg',
              caption: 'The Grand Album Cover'},
             {source:'app/images/wazoo02.jpg',
              caption: 'Use some shampoo, Frank'},
             {source:'app/images/wazoo03.jpg',
              caption: 'Live in Austin, 1977'},
             {source:'app/images/wazoo04.jpg',
              caption: 'Don\'t get any ideas'},
             {source:'app/images/wazoo05.jpg',
              caption: 'The Mothers of Invention'},
             {source:'app/images/wazoo06.jpg',
              caption: 'Sweet Shredding'}]
}, {
    albumName: 'Hot Hot Rods',
    photos: [{source:'app/images/car01.jpg',
              caption: 'Still drives! 18k OBO'},
             {source:'app/images/car02.jpg',
              caption: 'Minor alignment issues'},
             {source:'app/images/car03.jpg',
              caption: 'Some body work needed'},
             {source:'app/images/car04.jpg',
              caption: 'Great value!'}]
}, {
    albumName: 'Boring Ocean',
    photos: [{source:'app/images/ocean01.jpg',
              caption: 'Very boring'},
             {source:'app/images/ocean02.jpg',
              caption: 'Yawn'},
             {source:'app/images/ocean03.jpg',
              caption: 'Honestly dull and fake'}]
}, {
    albumName: 'All Bricks',
    photos: [{source:'app/images/brick01.jpg',
              caption: 'Red brick'},
             {source:'app/images/brick02.jpg',
              caption: 'White brick'},
             {source:'app/images/brick03.png',
              caption: 'Zany brick'},
             {source:'app/images/brick04.jpg',
              caption: 'Live at Brick'},
             {source:'app/images/brick05.jpg',
              caption: 'Ball don\'t lie'}]
}];
